"app/":
  - app_type:
    - "!automation"

"app/api/auth.py":
  - app_type:
    - portal

"app/auth.py":
  - app_type:
    - portal

"app/cache.py":
  - app_type:
    - portal

"automation/":
  - app_type:
    - automation
