services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src/app
    command: uvicorn main:app --reload
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - .env